// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteCommentDeleteComment, deleteLabelDeleteLabel, deleteTicketDeleteTicket, getCommentAllComments, getCommentByTicket, getCommentByTicketWithUser, getLabelAllLabels, getTicketAllTickets, getTicketAllTicketsDetail, getTicketByAssignee, getTicketByPriority, getTicketByStatus, getUserAgents, getUserAllUsers, getUserAllUsersWithTickets, type Options, patchTicketAssignTicket, patchTicketCloseTicket, patchTicketResolveTicket, patchTicketUpdatePriority, postCommentAddComment, postLabelCreateLabel, postTicketOpenTicket, postUserCreateUser } from '../sdk.gen';
import type { DeleteCommentDeleteCommentData, DeleteCommentDeleteCommentResponse, DeleteLabelDeleteLabelData, DeleteLabelDeleteLabelResponse, DeleteTicketDeleteTicketData, DeleteTicketDeleteTicketResponse, GetCommentAllCommentsData, GetCommentAllCommentsResponse, GetCommentByTicketData, GetCommentByTicketResponse, GetCommentByTicketWithUserData, GetCommentByTicketWithUserResponse, GetLabelAllLabelsData, GetLabelAllLabelsResponse, GetTicketAllTicketsData, GetTicketAllTicketsDetailData, GetTicketAllTicketsDetailResponse, GetTicketAllTicketsResponse, GetTicketByAssigneeData, GetTicketByAssigneeResponse, GetTicketByPriorityData, GetTicketByPriorityResponse, GetTicketByStatusData, GetTicketByStatusResponse, GetUserAgentsData, GetUserAgentsResponse, GetUserAllUsersData, GetUserAllUsersResponse, GetUserAllUsersWithTicketsData, GetUserAllUsersWithTicketsResponse, PatchTicketAssignTicketData, PatchTicketAssignTicketResponse, PatchTicketCloseTicketData, PatchTicketCloseTicketResponse, PatchTicketResolveTicketData, PatchTicketResolveTicketResponse, PatchTicketUpdatePriorityData, PatchTicketUpdatePriorityResponse, PostCommentAddCommentData, PostCommentAddCommentResponse, PostLabelCreateLabelData, PostLabelCreateLabelResponse, PostTicketOpenTicketData, PostTicketOpenTicketResponse, PostUserCreateUserData, PostUserCreateUserResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getCommentAllCommentsQueryKey = (options?: Options<GetCommentAllCommentsData>) => createQueryKey('getCommentAllComments', options);

/**
 * Read Comment via all_comments
 */
export const getCommentAllCommentsOptions = (options?: Options<GetCommentAllCommentsData>) => queryOptions<GetCommentAllCommentsResponse, DefaultError, GetCommentAllCommentsResponse, ReturnType<typeof getCommentAllCommentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCommentAllComments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCommentAllCommentsQueryKey(options)
});

/**
 * Create Comment via add_comment
 */
export const postCommentAddCommentMutation = (options?: Partial<Options<PostCommentAddCommentData>>): UseMutationOptions<PostCommentAddCommentResponse, DefaultError, Options<PostCommentAddCommentData>> => {
    const mutationOptions: UseMutationOptions<PostCommentAddCommentResponse, DefaultError, Options<PostCommentAddCommentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCommentAddComment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCommentByTicketQueryKey = (options: Options<GetCommentByTicketData>) => createQueryKey('getCommentByTicket', options);

/**
 * Read Comment via by_ticket
 */
export const getCommentByTicketOptions = (options: Options<GetCommentByTicketData>) => queryOptions<GetCommentByTicketResponse, DefaultError, GetCommentByTicketResponse, ReturnType<typeof getCommentByTicketQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCommentByTicket({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCommentByTicketQueryKey(options)
});

export const getCommentByTicketWithUserQueryKey = (options: Options<GetCommentByTicketWithUserData>) => createQueryKey('getCommentByTicketWithUser', options);

/**
 * Read Comment via by_ticket_with_user
 */
export const getCommentByTicketWithUserOptions = (options: Options<GetCommentByTicketWithUserData>) => queryOptions<GetCommentByTicketWithUserResponse, DefaultError, GetCommentByTicketWithUserResponse, ReturnType<typeof getCommentByTicketWithUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCommentByTicketWithUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCommentByTicketWithUserQueryKey(options)
});

/**
 * Destroy Comment via delete_comment
 */
export const deleteCommentDeleteCommentMutation = (options?: Partial<Options<DeleteCommentDeleteCommentData>>): UseMutationOptions<DeleteCommentDeleteCommentResponse, DefaultError, Options<DeleteCommentDeleteCommentData>> => {
    const mutationOptions: UseMutationOptions<DeleteCommentDeleteCommentResponse, DefaultError, Options<DeleteCommentDeleteCommentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCommentDeleteComment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getLabelAllLabelsQueryKey = (options?: Options<GetLabelAllLabelsData>) => createQueryKey('getLabelAllLabels', options);

/**
 * Read Label via all_labels
 */
export const getLabelAllLabelsOptions = (options?: Options<GetLabelAllLabelsData>) => queryOptions<GetLabelAllLabelsResponse, DefaultError, GetLabelAllLabelsResponse, ReturnType<typeof getLabelAllLabelsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLabelAllLabels({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLabelAllLabelsQueryKey(options)
});

/**
 * Create Label via create_label
 */
export const postLabelCreateLabelMutation = (options?: Partial<Options<PostLabelCreateLabelData>>): UseMutationOptions<PostLabelCreateLabelResponse, DefaultError, Options<PostLabelCreateLabelData>> => {
    const mutationOptions: UseMutationOptions<PostLabelCreateLabelResponse, DefaultError, Options<PostLabelCreateLabelData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postLabelCreateLabel({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Destroy Label via delete_label
 */
export const deleteLabelDeleteLabelMutation = (options?: Partial<Options<DeleteLabelDeleteLabelData>>): UseMutationOptions<DeleteLabelDeleteLabelResponse, DefaultError, Options<DeleteLabelDeleteLabelData>> => {
    const mutationOptions: UseMutationOptions<DeleteLabelDeleteLabelResponse, DefaultError, Options<DeleteLabelDeleteLabelData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteLabelDeleteLabel({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTicketAllTicketsQueryKey = (options?: Options<GetTicketAllTicketsData>) => createQueryKey('getTicketAllTickets', options);

/**
 * Paged read Ticket via all_tickets
 */
export const getTicketAllTicketsOptions = (options?: Options<GetTicketAllTicketsData>) => queryOptions<GetTicketAllTicketsResponse, DefaultError, GetTicketAllTicketsResponse, ReturnType<typeof getTicketAllTicketsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTicketAllTickets({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTicketAllTicketsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getTicketAllTicketsInfiniteQueryKey = (options?: Options<GetTicketAllTicketsData>): QueryKey<Options<GetTicketAllTicketsData>> => createQueryKey('getTicketAllTickets', options, true);

/**
 * Paged read Ticket via all_tickets
 */
export const getTicketAllTicketsInfiniteOptions = (options?: Options<GetTicketAllTicketsData>) => infiniteQueryOptions<GetTicketAllTicketsResponse, DefaultError, InfiniteData<GetTicketAllTicketsResponse>, QueryKey<Options<GetTicketAllTicketsData>>, number | Pick<QueryKey<Options<GetTicketAllTicketsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetTicketAllTicketsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getTicketAllTickets({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTicketAllTicketsInfiniteQueryKey(options)
});

/**
 * Create Ticket via open_ticket
 */
export const postTicketOpenTicketMutation = (options?: Partial<Options<PostTicketOpenTicketData>>): UseMutationOptions<PostTicketOpenTicketResponse, DefaultError, Options<PostTicketOpenTicketData>> => {
    const mutationOptions: UseMutationOptions<PostTicketOpenTicketResponse, DefaultError, Options<PostTicketOpenTicketData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postTicketOpenTicket({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTicketByAssigneeQueryKey = (options: Options<GetTicketByAssigneeData>) => createQueryKey('getTicketByAssignee', options);

/**
 * Read Ticket via by_assignee
 */
export const getTicketByAssigneeOptions = (options: Options<GetTicketByAssigneeData>) => queryOptions<GetTicketByAssigneeResponse, DefaultError, GetTicketByAssigneeResponse, ReturnType<typeof getTicketByAssigneeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTicketByAssignee({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTicketByAssigneeQueryKey(options)
});

export const getTicketByPriorityQueryKey = (options: Options<GetTicketByPriorityData>) => createQueryKey('getTicketByPriority', options);

/**
 * Read Ticket via by_priority
 */
export const getTicketByPriorityOptions = (options: Options<GetTicketByPriorityData>) => queryOptions<GetTicketByPriorityResponse, DefaultError, GetTicketByPriorityResponse, ReturnType<typeof getTicketByPriorityQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTicketByPriority({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTicketByPriorityQueryKey(options)
});

export const getTicketByStatusQueryKey = (options: Options<GetTicketByStatusData>) => createQueryKey('getTicketByStatus', options);

/**
 * Paged read Ticket via by_status
 */
export const getTicketByStatusOptions = (options: Options<GetTicketByStatusData>) => queryOptions<GetTicketByStatusResponse, DefaultError, GetTicketByStatusResponse, ReturnType<typeof getTicketByStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTicketByStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTicketByStatusQueryKey(options)
});

export const getTicketByStatusInfiniteQueryKey = (options: Options<GetTicketByStatusData>): QueryKey<Options<GetTicketByStatusData>> => createQueryKey('getTicketByStatus', options, true);

/**
 * Paged read Ticket via by_status
 */
export const getTicketByStatusInfiniteOptions = (options: Options<GetTicketByStatusData>) => infiniteQueryOptions<GetTicketByStatusResponse, DefaultError, InfiniteData<GetTicketByStatusResponse>, QueryKey<Options<GetTicketByStatusData>>, number | Pick<QueryKey<Options<GetTicketByStatusData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetTicketByStatusData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getTicketByStatus({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTicketByStatusInfiniteQueryKey(options)
});

export const getTicketAllTicketsDetailQueryKey = (options?: Options<GetTicketAllTicketsDetailData>) => createQueryKey('getTicketAllTicketsDetail', options);

/**
 * Read Ticket via all_tickets_detail
 */
export const getTicketAllTicketsDetailOptions = (options?: Options<GetTicketAllTicketsDetailData>) => queryOptions<GetTicketAllTicketsDetailResponse, DefaultError, GetTicketAllTicketsDetailResponse, ReturnType<typeof getTicketAllTicketsDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTicketAllTicketsDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTicketAllTicketsDetailQueryKey(options)
});

/**
 * Destroy Ticket via delete_ticket
 */
export const deleteTicketDeleteTicketMutation = (options?: Partial<Options<DeleteTicketDeleteTicketData>>): UseMutationOptions<DeleteTicketDeleteTicketResponse, DefaultError, Options<DeleteTicketDeleteTicketData>> => {
    const mutationOptions: UseMutationOptions<DeleteTicketDeleteTicketResponse, DefaultError, Options<DeleteTicketDeleteTicketData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteTicketDeleteTicket({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Ticket via assign_ticket
 */
export const patchTicketAssignTicketMutation = (options?: Partial<Options<PatchTicketAssignTicketData>>): UseMutationOptions<PatchTicketAssignTicketResponse, DefaultError, Options<PatchTicketAssignTicketData>> => {
    const mutationOptions: UseMutationOptions<PatchTicketAssignTicketResponse, DefaultError, Options<PatchTicketAssignTicketData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchTicketAssignTicket({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Ticket via close_ticket
 */
export const patchTicketCloseTicketMutation = (options?: Partial<Options<PatchTicketCloseTicketData>>): UseMutationOptions<PatchTicketCloseTicketResponse, DefaultError, Options<PatchTicketCloseTicketData>> => {
    const mutationOptions: UseMutationOptions<PatchTicketCloseTicketResponse, DefaultError, Options<PatchTicketCloseTicketData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchTicketCloseTicket({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Ticket via update_priority
 */
export const patchTicketUpdatePriorityMutation = (options?: Partial<Options<PatchTicketUpdatePriorityData>>): UseMutationOptions<PatchTicketUpdatePriorityResponse, DefaultError, Options<PatchTicketUpdatePriorityData>> => {
    const mutationOptions: UseMutationOptions<PatchTicketUpdatePriorityResponse, DefaultError, Options<PatchTicketUpdatePriorityData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchTicketUpdatePriority({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Update Ticket via resolve_ticket
 */
export const patchTicketResolveTicketMutation = (options?: Partial<Options<PatchTicketResolveTicketData>>): UseMutationOptions<PatchTicketResolveTicketResponse, DefaultError, Options<PatchTicketResolveTicketData>> => {
    const mutationOptions: UseMutationOptions<PatchTicketResolveTicketResponse, DefaultError, Options<PatchTicketResolveTicketData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchTicketResolveTicket({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserAllUsersQueryKey = (options?: Options<GetUserAllUsersData>) => createQueryKey('getUserAllUsers', options);

/**
 * Read User via all_users
 */
export const getUserAllUsersOptions = (options?: Options<GetUserAllUsersData>) => queryOptions<GetUserAllUsersResponse, DefaultError, GetUserAllUsersResponse, ReturnType<typeof getUserAllUsersQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserAllUsers({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserAllUsersQueryKey(options)
});

/**
 * Create User via create_user
 */
export const postUserCreateUserMutation = (options?: Partial<Options<PostUserCreateUserData>>): UseMutationOptions<PostUserCreateUserResponse, DefaultError, Options<PostUserCreateUserData>> => {
    const mutationOptions: UseMutationOptions<PostUserCreateUserResponse, DefaultError, Options<PostUserCreateUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postUserCreateUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserAgentsQueryKey = (options?: Options<GetUserAgentsData>) => createQueryKey('getUserAgents', options);

/**
 * Read User via agents
 */
export const getUserAgentsOptions = (options?: Options<GetUserAgentsData>) => queryOptions<GetUserAgentsResponse, DefaultError, GetUserAgentsResponse, ReturnType<typeof getUserAgentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserAgents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserAgentsQueryKey(options)
});

export const getUserAllUsersWithTicketsQueryKey = (options?: Options<GetUserAllUsersWithTicketsData>) => createQueryKey('getUserAllUsersWithTickets', options);

/**
 * Read User via all_users_with_tickets
 */
export const getUserAllUsersWithTicketsOptions = (options?: Options<GetUserAllUsersWithTicketsData>) => queryOptions<GetUserAllUsersWithTicketsResponse, DefaultError, GetUserAllUsersWithTicketsResponse, ReturnType<typeof getUserAllUsersWithTicketsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserAllUsersWithTickets({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserAllUsersWithTicketsQueryKey(options)
});
