// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteCommentDeleteCommentData, DeleteCommentDeleteCommentResponses, DeleteLabelDeleteLabelData, DeleteLabelDeleteLabelResponses, DeleteTicketDeleteTicketData, DeleteTicketDeleteTicketResponses, GetCommentAllCommentsData, GetCommentAllCommentsResponses, GetCommentByTicketData, GetCommentByTicketResponses, GetCommentByTicketWithUserData, GetCommentByTicketWithUserResponses, GetLabelAllLabelsData, GetLabelAllLabelsResponses, GetTicketAllTicketsData, GetTicketAllTicketsDetailData, GetTicketAllTicketsDetailResponses, GetTicketAllTicketsResponses, GetTicketByAssigneeData, GetTicketByAssigneeResponses, GetTicketByPriorityData, GetTicketByPriorityResponses, GetTicketByStatusData, GetTicketByStatusResponses, GetUserAgentsData, GetUserAgentsResponses, GetUserAllUsersData, GetUserAllUsersResponses, GetUserAllUsersWithTicketsData, GetUserAllUsersWithTicketsResponses, PatchTicketAssignTicketData, PatchTicketAssignTicketResponses, PatchTicketCloseTicketData, PatchTicketCloseTicketResponses, PatchTicketResolveTicketData, PatchTicketResolveTicketResponses, PatchTicketUpdatePriorityData, PatchTicketUpdatePriorityResponses, PostCommentAddCommentData, PostCommentAddCommentResponses, PostLabelCreateLabelData, PostLabelCreateLabelResponses, PostTicketOpenTicketData, PostTicketOpenTicketResponses, PostUserCreateUserData, PostUserCreateUserResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Read Comment via all_comments
 */
export const getCommentAllComments = <ThrowOnError extends boolean = false>(options?: Options<GetCommentAllCommentsData, ThrowOnError>) => (options?.client ?? client).get<GetCommentAllCommentsResponses, unknown, ThrowOnError>({ url: '/ticketing/support/comment/', ...options });

/**
 * Create Comment via add_comment
 */
export const postCommentAddComment = <ThrowOnError extends boolean = false>(options: Options<PostCommentAddCommentData, ThrowOnError>) => (options.client ?? client).post<PostCommentAddCommentResponses, unknown, ThrowOnError>({
    url: '/ticketing/support/comment/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Comment via by_ticket
 */
export const getCommentByTicket = <ThrowOnError extends boolean = false>(options: Options<GetCommentByTicketData, ThrowOnError>) => (options.client ?? client).get<GetCommentByTicketResponses, unknown, ThrowOnError>({ url: '/ticketing/support/comment/by-ticket', ...options });

/**
 * Read Comment via by_ticket_with_user
 */
export const getCommentByTicketWithUser = <ThrowOnError extends boolean = false>(options: Options<GetCommentByTicketWithUserData, ThrowOnError>) => (options.client ?? client).get<GetCommentByTicketWithUserResponses, unknown, ThrowOnError>({ url: '/ticketing/support/comment/by-ticket/with-user', ...options });

/**
 * Destroy Comment via delete_comment
 */
export const deleteCommentDeleteComment = <ThrowOnError extends boolean = false>(options: Options<DeleteCommentDeleteCommentData, ThrowOnError>) => (options.client ?? client).delete<DeleteCommentDeleteCommentResponses, unknown, ThrowOnError>({ url: '/ticketing/support/comment/{primary_key}', ...options });

/**
 * Read Label via all_labels
 */
export const getLabelAllLabels = <ThrowOnError extends boolean = false>(options?: Options<GetLabelAllLabelsData, ThrowOnError>) => (options?.client ?? client).get<GetLabelAllLabelsResponses, unknown, ThrowOnError>({ url: '/ticketing/support/label/', ...options });

/**
 * Create Label via create_label
 */
export const postLabelCreateLabel = <ThrowOnError extends boolean = false>(options: Options<PostLabelCreateLabelData, ThrowOnError>) => (options.client ?? client).post<PostLabelCreateLabelResponses, unknown, ThrowOnError>({
    url: '/ticketing/support/label/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Destroy Label via delete_label
 */
export const deleteLabelDeleteLabel = <ThrowOnError extends boolean = false>(options: Options<DeleteLabelDeleteLabelData, ThrowOnError>) => (options.client ?? client).delete<DeleteLabelDeleteLabelResponses, unknown, ThrowOnError>({ url: '/ticketing/support/label/{primary_key}', ...options });

/**
 * Paged read Ticket via all_tickets
 */
export const getTicketAllTickets = <ThrowOnError extends boolean = false>(options?: Options<GetTicketAllTicketsData, ThrowOnError>) => (options?.client ?? client).get<GetTicketAllTicketsResponses, unknown, ThrowOnError>({ url: '/ticketing/support/ticket/', ...options });

/**
 * Create Ticket via open_ticket
 */
export const postTicketOpenTicket = <ThrowOnError extends boolean = false>(options: Options<PostTicketOpenTicketData, ThrowOnError>) => (options.client ?? client).post<PostTicketOpenTicketResponses, unknown, ThrowOnError>({
    url: '/ticketing/support/ticket/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read Ticket via by_assignee
 */
export const getTicketByAssignee = <ThrowOnError extends boolean = false>(options: Options<GetTicketByAssigneeData, ThrowOnError>) => (options.client ?? client).get<GetTicketByAssigneeResponses, unknown, ThrowOnError>({ url: '/ticketing/support/ticket/by-assignee', ...options });

/**
 * Read Ticket via by_priority
 */
export const getTicketByPriority = <ThrowOnError extends boolean = false>(options: Options<GetTicketByPriorityData, ThrowOnError>) => (options.client ?? client).get<GetTicketByPriorityResponses, unknown, ThrowOnError>({ url: '/ticketing/support/ticket/by-priority', ...options });

/**
 * Paged read Ticket via by_status
 */
export const getTicketByStatus = <ThrowOnError extends boolean = false>(options: Options<GetTicketByStatusData, ThrowOnError>) => (options.client ?? client).get<GetTicketByStatusResponses, unknown, ThrowOnError>({ url: '/ticketing/support/ticket/by-status', ...options });

/**
 * Read Ticket via all_tickets_detail
 */
export const getTicketAllTicketsDetail = <ThrowOnError extends boolean = false>(options?: Options<GetTicketAllTicketsDetailData, ThrowOnError>) => (options?.client ?? client).get<GetTicketAllTicketsDetailResponses, unknown, ThrowOnError>({ url: '/ticketing/support/ticket/detail', ...options });

/**
 * Destroy Ticket via delete_ticket
 */
export const deleteTicketDeleteTicket = <ThrowOnError extends boolean = false>(options: Options<DeleteTicketDeleteTicketData, ThrowOnError>) => (options.client ?? client).delete<DeleteTicketDeleteTicketResponses, unknown, ThrowOnError>({ url: '/ticketing/support/ticket/{primary_key}', ...options });

/**
 * Update Ticket via assign_ticket
 */
export const patchTicketAssignTicket = <ThrowOnError extends boolean = false>(options: Options<PatchTicketAssignTicketData, ThrowOnError>) => (options.client ?? client).patch<PatchTicketAssignTicketResponses, unknown, ThrowOnError>({
    url: '/ticketing/support/ticket/{primary_key}/assign',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Ticket via close_ticket
 */
export const patchTicketCloseTicket = <ThrowOnError extends boolean = false>(options: Options<PatchTicketCloseTicketData, ThrowOnError>) => (options.client ?? client).patch<PatchTicketCloseTicketResponses, unknown, ThrowOnError>({
    url: '/ticketing/support/ticket/{primary_key}/close',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Ticket via update_priority
 */
export const patchTicketUpdatePriority = <ThrowOnError extends boolean = false>(options: Options<PatchTicketUpdatePriorityData, ThrowOnError>) => (options.client ?? client).patch<PatchTicketUpdatePriorityResponses, unknown, ThrowOnError>({
    url: '/ticketing/support/ticket/{primary_key}/priority',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Update Ticket via resolve_ticket
 */
export const patchTicketResolveTicket = <ThrowOnError extends boolean = false>(options: Options<PatchTicketResolveTicketData, ThrowOnError>) => (options.client ?? client).patch<PatchTicketResolveTicketResponses, unknown, ThrowOnError>({
    url: '/ticketing/support/ticket/{primary_key}/resolve',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read User via all_users
 */
export const getUserAllUsers = <ThrowOnError extends boolean = false>(options?: Options<GetUserAllUsersData, ThrowOnError>) => (options?.client ?? client).get<GetUserAllUsersResponses, unknown, ThrowOnError>({ url: '/ticketing/support/user/', ...options });

/**
 * Create User via create_user
 */
export const postUserCreateUser = <ThrowOnError extends boolean = false>(options: Options<PostUserCreateUserData, ThrowOnError>) => (options.client ?? client).post<PostUserCreateUserResponses, unknown, ThrowOnError>({
    url: '/ticketing/support/user/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read User via agents
 */
export const getUserAgents = <ThrowOnError extends boolean = false>(options?: Options<GetUserAgentsData, ThrowOnError>) => (options?.client ?? client).get<GetUserAgentsResponses, unknown, ThrowOnError>({ url: '/ticketing/support/user/agents', ...options });

/**
 * Read User via all_users_with_tickets
 */
export const getUserAllUsersWithTickets = <ThrowOnError extends boolean = false>(options?: Options<GetUserAllUsersWithTicketsData, ThrowOnError>) => (options?.client ?? client).get<GetUserAllUsersWithTicketsResponses, unknown, ThrowOnError>({ url: '/ticketing/support/user/with-tickets', ...options });
