// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AddCommentInput = {
    body: string;
    ticket_id: string;
    user_id: string;
};

export type AssignTicketInput = {
    assignee_id: string;
};

export type CloseTicketInput = {
    [key: string]: unknown;
};

export type Comment = {
    body: string;
    comment_id: string;
    created_at: string;
    ticket_id: string;
    user_id: string;
};

export type CreateLabelInput = {
    color: string;
    name: string;
};

export type CreateUserInput = {
    email: string;
    name: string;
    role: 'Admin' | 'Agent' | 'Customer';
};

export type Label = {
    color: string;
    label_id: string;
    name: string;
};

export type OpenTicketInput = {
    assignee_id: string;
    description?: string | null;
    label_id: string;
    priority: 'Low' | 'Medium' | 'High' | 'Urgent';
    reporter_id: string;
    status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
    subject: string;
};

export type ResolveTicketInput = {
    [key: string]: unknown;
};

export type Ticket = {
    assignee_id: string;
    created_at: string;
    description?: string | null;
    label_id: string;
    priority: 'Low' | 'Medium' | 'High' | 'Urgent';
    reporter_id: string;
    status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
    subject: string;
    ticket_id: string;
};

export type UpdatePriorityInput = {
    priority: 'Low' | 'Medium' | 'High' | 'Urgent';
};

export type User = {
    email: string;
    name: string;
    role: 'Admin' | 'Agent' | 'Customer';
    user_id: string;
};

export type GetCommentAllCommentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ticketing/support/comment/';
};

export type GetCommentAllCommentsResponses = {
    /**
     * Filtered list of Comments
     */
    200: {
        data: Array<{
            body: string;
            comment_id: string;
            created_at: string;
            ticket_id: string;
            user_id: string;
        }>;
    };
};

export type GetCommentAllCommentsResponse = GetCommentAllCommentsResponses[keyof GetCommentAllCommentsResponses];

export type PostCommentAddCommentData = {
    body: {
        body: string;
        ticket_id: string;
        user_id: string;
    };
    path?: never;
    query?: never;
    url: '/ticketing/support/comment/';
};

export type PostCommentAddCommentResponses = {
    /**
     * Comment created
     */
    201: {
        data: {
            body: string;
            comment_id: string;
            created_at: string;
            ticket_id: string;
            user_id: string;
        };
    };
};

export type PostCommentAddCommentResponse = PostCommentAddCommentResponses[keyof PostCommentAddCommentResponses];

export type GetCommentByTicketData = {
    body?: never;
    path?: never;
    query: {
        ticket_id: string;
    };
    url: '/ticketing/support/comment/by-ticket';
};

export type GetCommentByTicketResponses = {
    /**
     * Filtered list of Comments
     */
    200: {
        data: Array<{
            body: string;
            comment_id: string;
            created_at: string;
            ticket_id: string;
            user_id: string;
        }>;
    };
};

export type GetCommentByTicketResponse = GetCommentByTicketResponses[keyof GetCommentByTicketResponses];

export type GetCommentByTicketWithUserData = {
    body?: never;
    path?: never;
    query: {
        ticket_id: string;
    };
    url: '/ticketing/support/comment/by-ticket/with-user';
};

export type GetCommentByTicketWithUserResponses = {
    /**
     * Filtered list of Comments
     */
    200: {
        data: Array<{
            body: string;
            comment_id: string;
            created_at: string;
            ticket_id: string;
            user_id: string;
        }>;
    };
};

export type GetCommentByTicketWithUserResponse = GetCommentByTicketWithUserResponses[keyof GetCommentByTicketWithUserResponses];

export type DeleteCommentDeleteCommentData = {
    body?: never;
    path: {
        primary_key: string;
    };
    query?: never;
    url: '/ticketing/support/comment/{primary_key}';
};

export type DeleteCommentDeleteCommentResponses = {
    /**
     * Comment destroyed
     */
    204: void;
};

export type DeleteCommentDeleteCommentResponse = DeleteCommentDeleteCommentResponses[keyof DeleteCommentDeleteCommentResponses];

export type GetLabelAllLabelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ticketing/support/label/';
};

export type GetLabelAllLabelsResponses = {
    /**
     * Filtered list of Labels
     */
    200: {
        data: Array<{
            color: string;
            label_id: string;
            name: string;
        }>;
    };
};

export type GetLabelAllLabelsResponse = GetLabelAllLabelsResponses[keyof GetLabelAllLabelsResponses];

export type PostLabelCreateLabelData = {
    body: {
        color: string;
        name: string;
    };
    path?: never;
    query?: never;
    url: '/ticketing/support/label/';
};

export type PostLabelCreateLabelResponses = {
    /**
     * Label created
     */
    201: {
        data: {
            color: string;
            label_id: string;
            name: string;
        };
    };
};

export type PostLabelCreateLabelResponse = PostLabelCreateLabelResponses[keyof PostLabelCreateLabelResponses];

export type DeleteLabelDeleteLabelData = {
    body?: never;
    path: {
        primary_key: string;
    };
    query?: never;
    url: '/ticketing/support/label/{primary_key}';
};

export type DeleteLabelDeleteLabelResponses = {
    /**
     * Label destroyed
     */
    204: void;
};

export type DeleteLabelDeleteLabelResponse = DeleteLabelDeleteLabelResponses[keyof DeleteLabelDeleteLabelResponses];

export type GetTicketAllTicketsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-indexed, default: 1)
         */
        page?: number;
        /**
         * Items per page
         */
        per_page?: number;
    };
    url: '/ticketing/support/ticket/';
};

export type GetTicketAllTicketsResponses = {
    /**
     * Filtered list of Tickets
     */
    200: {
        data: Array<{
            assignee_id: string;
            created_at: string;
            description?: string | null;
            label_id: string;
            priority: 'Low' | 'Medium' | 'High' | 'Urgent';
            reporter_id: string;
            status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
            subject: string;
            ticket_id: string;
        }>;
        meta: {
            page: number;
            per_page: number;
            total: number;
            total_pages: number;
        };
    };
};

export type GetTicketAllTicketsResponse = GetTicketAllTicketsResponses[keyof GetTicketAllTicketsResponses];

export type PostTicketOpenTicketData = {
    body: {
        assignee_id: string;
        description?: string | null;
        label_id: string;
        priority: 'Low' | 'Medium' | 'High' | 'Urgent';
        reporter_id: string;
        status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
        subject: string;
    };
    path?: never;
    query?: never;
    url: '/ticketing/support/ticket/';
};

export type PostTicketOpenTicketResponses = {
    /**
     * Ticket created
     */
    201: {
        data: {
            assignee_id: string;
            created_at: string;
            description?: string | null;
            label_id: string;
            priority: 'Low' | 'Medium' | 'High' | 'Urgent';
            reporter_id: string;
            status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
            subject: string;
            ticket_id: string;
        };
    };
};

export type PostTicketOpenTicketResponse = PostTicketOpenTicketResponses[keyof PostTicketOpenTicketResponses];

export type GetTicketByAssigneeData = {
    body?: never;
    path?: never;
    query: {
        assignee_id: string;
    };
    url: '/ticketing/support/ticket/by-assignee';
};

export type GetTicketByAssigneeResponses = {
    /**
     * Filtered list of Tickets
     */
    200: {
        data: Array<{
            assignee_id: string;
            created_at: string;
            description?: string | null;
            label_id: string;
            priority: 'Low' | 'Medium' | 'High' | 'Urgent';
            reporter_id: string;
            status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
            subject: string;
            ticket_id: string;
        }>;
    };
};

export type GetTicketByAssigneeResponse = GetTicketByAssigneeResponses[keyof GetTicketByAssigneeResponses];

export type GetTicketByPriorityData = {
    body?: never;
    path?: never;
    query: {
        priority: 'Low' | 'Medium' | 'High' | 'Urgent';
    };
    url: '/ticketing/support/ticket/by-priority';
};

export type GetTicketByPriorityResponses = {
    /**
     * Filtered list of Tickets
     */
    200: {
        data: Array<{
            assignee_id: string;
            created_at: string;
            description?: string | null;
            label_id: string;
            priority: 'Low' | 'Medium' | 'High' | 'Urgent';
            reporter_id: string;
            status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
            subject: string;
            ticket_id: string;
        }>;
    };
};

export type GetTicketByPriorityResponse = GetTicketByPriorityResponses[keyof GetTicketByPriorityResponses];

export type GetTicketByStatusData = {
    body?: never;
    path?: never;
    query: {
        status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
        /**
         * Page number (1-indexed, default: 1)
         */
        page?: number;
        /**
         * Items per page
         */
        per_page?: number;
    };
    url: '/ticketing/support/ticket/by-status';
};

export type GetTicketByStatusResponses = {
    /**
     * Filtered list of Tickets
     */
    200: {
        data: Array<{
            assignee_id: string;
            created_at: string;
            description?: string | null;
            label_id: string;
            priority: 'Low' | 'Medium' | 'High' | 'Urgent';
            reporter_id: string;
            status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
            subject: string;
            ticket_id: string;
        }>;
        meta: {
            page: number;
            per_page: number;
            total: number;
            total_pages: number;
        };
    };
};

export type GetTicketByStatusResponse = GetTicketByStatusResponses[keyof GetTicketByStatusResponses];

export type GetTicketAllTicketsDetailData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ticketing/support/ticket/detail';
};

export type GetTicketAllTicketsDetailResponses = {
    /**
     * Filtered list of Tickets
     */
    200: {
        data: Array<{
            assignee_id: string;
            created_at: string;
            description?: string | null;
            label_id: string;
            priority: 'Low' | 'Medium' | 'High' | 'Urgent';
            reporter_id: string;
            status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
            subject: string;
            ticket_id: string;
        }>;
    };
};

export type GetTicketAllTicketsDetailResponse = GetTicketAllTicketsDetailResponses[keyof GetTicketAllTicketsDetailResponses];

export type DeleteTicketDeleteTicketData = {
    body?: never;
    path: {
        primary_key: string;
    };
    query?: never;
    url: '/ticketing/support/ticket/{primary_key}';
};

export type DeleteTicketDeleteTicketResponses = {
    /**
     * Ticket destroyed
     */
    204: void;
};

export type DeleteTicketDeleteTicketResponse = DeleteTicketDeleteTicketResponses[keyof DeleteTicketDeleteTicketResponses];

export type PatchTicketAssignTicketData = {
    body: {
        assignee_id: string;
    };
    path: {
        primary_key: string;
    };
    query?: never;
    url: '/ticketing/support/ticket/{primary_key}/assign';
};

export type PatchTicketAssignTicketResponses = {
    /**
     * Ticket updated
     */
    200: {
        data: {
            assignee_id: string;
            created_at: string;
            description?: string | null;
            label_id: string;
            priority: 'Low' | 'Medium' | 'High' | 'Urgent';
            reporter_id: string;
            status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
            subject: string;
            ticket_id: string;
        };
    };
};

export type PatchTicketAssignTicketResponse = PatchTicketAssignTicketResponses[keyof PatchTicketAssignTicketResponses];

export type PatchTicketCloseTicketData = {
    body?: {
        [key: string]: unknown;
    };
    path: {
        primary_key: string;
    };
    query?: never;
    url: '/ticketing/support/ticket/{primary_key}/close';
};

export type PatchTicketCloseTicketResponses = {
    /**
     * Ticket updated
     */
    200: {
        data: {
            assignee_id: string;
            created_at: string;
            description?: string | null;
            label_id: string;
            priority: 'Low' | 'Medium' | 'High' | 'Urgent';
            reporter_id: string;
            status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
            subject: string;
            ticket_id: string;
        };
    };
};

export type PatchTicketCloseTicketResponse = PatchTicketCloseTicketResponses[keyof PatchTicketCloseTicketResponses];

export type PatchTicketUpdatePriorityData = {
    body: {
        priority: 'Low' | 'Medium' | 'High' | 'Urgent';
    };
    path: {
        primary_key: string;
    };
    query?: never;
    url: '/ticketing/support/ticket/{primary_key}/priority';
};

export type PatchTicketUpdatePriorityResponses = {
    /**
     * Ticket updated
     */
    200: {
        data: {
            assignee_id: string;
            created_at: string;
            description?: string | null;
            label_id: string;
            priority: 'Low' | 'Medium' | 'High' | 'Urgent';
            reporter_id: string;
            status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
            subject: string;
            ticket_id: string;
        };
    };
};

export type PatchTicketUpdatePriorityResponse = PatchTicketUpdatePriorityResponses[keyof PatchTicketUpdatePriorityResponses];

export type PatchTicketResolveTicketData = {
    body?: {
        [key: string]: unknown;
    };
    path: {
        primary_key: string;
    };
    query?: never;
    url: '/ticketing/support/ticket/{primary_key}/resolve';
};

export type PatchTicketResolveTicketResponses = {
    /**
     * Ticket updated
     */
    200: {
        data: {
            assignee_id: string;
            created_at: string;
            description?: string | null;
            label_id: string;
            priority: 'Low' | 'Medium' | 'High' | 'Urgent';
            reporter_id: string;
            status: 'Open' | 'InProgress' | 'Resolved' | 'Closed';
            subject: string;
            ticket_id: string;
        };
    };
};

export type PatchTicketResolveTicketResponse = PatchTicketResolveTicketResponses[keyof PatchTicketResolveTicketResponses];

export type GetUserAllUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ticketing/support/user/';
};

export type GetUserAllUsersResponses = {
    /**
     * Filtered list of Users
     */
    200: {
        data: Array<{
            email: string;
            name: string;
            role: 'Admin' | 'Agent' | 'Customer';
            user_id: string;
        }>;
    };
};

export type GetUserAllUsersResponse = GetUserAllUsersResponses[keyof GetUserAllUsersResponses];

export type PostUserCreateUserData = {
    body: {
        email: string;
        name: string;
        role: 'Admin' | 'Agent' | 'Customer';
    };
    path?: never;
    query?: never;
    url: '/ticketing/support/user/';
};

export type PostUserCreateUserResponses = {
    /**
     * User created
     */
    201: {
        data: {
            email: string;
            name: string;
            role: 'Admin' | 'Agent' | 'Customer';
            user_id: string;
        };
    };
};

export type PostUserCreateUserResponse = PostUserCreateUserResponses[keyof PostUserCreateUserResponses];

export type GetUserAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ticketing/support/user/agents';
};

export type GetUserAgentsResponses = {
    /**
     * Filtered list of Users
     */
    200: {
        data: Array<{
            email: string;
            name: string;
            role: 'Admin' | 'Agent' | 'Customer';
            user_id: string;
        }>;
    };
};

export type GetUserAgentsResponse = GetUserAgentsResponses[keyof GetUserAgentsResponses];

export type GetUserAllUsersWithTicketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ticketing/support/user/with-tickets';
};

export type GetUserAllUsersWithTicketsResponses = {
    /**
     * Filtered list of Users
     */
    200: {
        data: Array<{
            email: string;
            name: string;
            role: 'Admin' | 'Agent' | 'Customer';
            user_id: string;
        }>;
    };
};

export type GetUserAllUsersWithTicketsResponse = GetUserAllUsersWithTicketsResponses[keyof GetUserAllUsersWithTicketsResponses];
